---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ngnx-app
  namespace: flux-system-test
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/Sangauppe/flux-ngnix-sot
