---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-ngnix-sot
  namespace: default
spec:
  interval: 30s
  path: ./deoloy
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-ngnix-sot
  timeout: 3m0s
  wait: true
